Remove test result publishing (to be split out).

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -60,13 +60,13 @@ jobs:
             extra-substituters = https://cache.iog.io file://${{ runner.temp }}/nix-binary-cache
             accept-flake-config = true
 
-      - name: Cache Nix
-        uses: input-output-hk/actions/attic@latest
-        with:
-          nix_path: nixpkgs=channel:nixos-unstable
-          endpoint: https://attic.ci.iog.io
-          cache: midnight
-          access_token: ${{ secrets.ATTIC_CACHE_TOKEN }}
+      #- name: Cache Nix
+      #  uses: input-output-hk/actions/attic@latest
+      #  with:
+      #    nix_path: nixpkgs=channel:nixos-unstable
+      #    endpoint: https://attic.ci.iog.io
+      #    cache: midnight
+      #    access_token: ${{ secrets.ATTIC_CACHE_TOKEN }}
 
       - name: Fix Nix permissions (needed on macos self hosted runner)
         run: |
@@ -217,13 +217,13 @@ jobs:
             extra-substituters = https://cache.iog.io file://${{ runner.temp }}/nix-binary-cache
             accept-flake-config = true
 
-      - name: Cache Nix
-        uses: input-output-hk/actions/attic@latest
-        with:
-          nix_path: nixpkgs=channel:nixos-unstable
-          endpoint: https://attic.ci.iog.io
-          cache: midnight
-          access_token: ${{ secrets.ATTIC_CACHE_TOKEN }}
+      #- name: Cache Nix
+      #  uses: input-output-hk/actions/attic@latest
+      #  with:
+      #    nix_path: nixpkgs=channel:nixos-unstable
+      #    endpoint: https://attic.ci.iog.io
+      #    cache: midnight
+      #    access_token: ${{ secrets.ATTIC_CACHE_TOKEN }}
 
       - name: Configure cargo
         run: .github/scripts/configure-cargo.sh
@@ -283,28 +283,28 @@ jobs:
         run: |
           nix develop .#ci -c cargo spellcheck -j1
 
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@97744eca465b8df9e6e33271cb155003f85327f1
-        if: success() || failure()
-        with:
-          check_name: 'Proof Server - JUnit Test Results - ${{ matrix.runner }}'
-          report_paths: '**/target/test-*.xml'
+      #- name: Publish Test Report
+      #  uses: mikepenz/action-junit-report@97744eca465b8df9e6e33271cb155003f85327f1
+      #  if: success() || failure()
+      #  with:
+      #    check_name: 'Proof Server - JUnit Test Results - ${{ matrix.runner }}'
+      #    report_paths: '**/target/test-*.xml'
 
-      - name: Publish Test Summary
-        uses: EnricoMi/publish-unit-test-result-action@170bf24d20d201b842d7a52403b73ed297e6645b
-        if: always() && matrix.runner != 'self-hosted'
-        with:
-          check_name: 'Proof Server - Test Results - ${{ matrix.runner }}'
-          files: |
-            **/target/test-*.xml
+      #- name: Publish Test Summary
+      #  uses: EnricoMi/publish-unit-test-result-action@170bf24d20d201b842d7a52403b73ed297e6645b
+      #  if: always() && matrix.runner != 'self-hosted'
+      #  with:
+      #    check_name: 'Proof Server - Test Results - ${{ matrix.runner }}'
+      #    files: |
+      #      **/target/test-*.xml
 
-      - name: Publish Test Summary
-        uses: EnricoMi/publish-unit-test-result-action/macos@170bf24d20d201b842d7a52403b73ed297e6645b
-        if: always() && matrix.runner == 'self-hosted'
-        with:
-          check_name: 'Proof Server - Test Results - ${{ matrix.runner }}'
-          files: |
-            **/target/test-*.xml
+      #- name: Publish Test Summary
+      #  uses: EnricoMi/publish-unit-test-result-action/macos@170bf24d20d201b842d7a52403b73ed297e6645b
+      #  if: always() && matrix.runner == 'self-hosted'
+      #  with:
+      #    check_name: 'Proof Server - Test Results - ${{ matrix.runner }}'
+      #    files: |
+      #      **/target/test-*.xml
 
       - name: Upload Artifact
         uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
