Tear out IT-test report too.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -83,7 +83,6 @@ jobs:
 
       - name: Build and Test
         run: |
-          nix develop .#ci -c cargo config -Z unstable-options get net.git-fetch-with-cli
           nix build -L --max-jobs 1
 
       - name: Add Homebrew and git bin to PATH for Yarn, verify git is installed
@@ -114,50 +113,50 @@ jobs:
          name: logs-${{ matrix.runner }}
          path: integration-tests/logs/
 
-      - name: Publish IT Test Report
-        uses: mikepenz/action-junit-report@97744eca465b8df9e6e33271cb155003f85327f1
-        if: success() || failure()
-        with:
-          check_name: 'IT Test Report - ${{ matrix.runner }}'
-          report_paths: '**/reports/test-*.xml'
+      #- name: Publish IT Test Report
+      #  uses: mikepenz/action-junit-report@97744eca465b8df9e6e33271cb155003f85327f1
+      #  if: success() || failure()
+      #  with:
+      #    check_name: 'IT Test Report - ${{ matrix.runner }}'
+      #    report_paths: '**/reports/test-*.xml'
 
-      - name: Publish Test Coverage
-        uses: MishaKav/jest-coverage-comment@d74238813c33e6ea20530ff91b5ea37953d11c91
-        with:
-          title: 'Integration tests summary - ${{ matrix.runner }}'
-          unique-id-for-comment: ${{ matrix.runner }}
-          coverage-summary-path: ./integration-tests/coverage/coverage-summary.json
-          junitxml-path: ./integration-tests/reports/test-report.xml
-          coverage-path: ./integration-tests/coverage.txt
+      #- name: Publish Test Coverage
+      #  uses: MishaKav/jest-coverage-comment@d74238813c33e6ea20530ff91b5ea37953d11c91
+      #  with:
+      #    title: 'Integration tests summary - ${{ matrix.runner }}'
+      #    unique-id-for-comment: ${{ matrix.runner }}
+      #    coverage-summary-path: ./integration-tests/coverage/coverage-summary.json
+      #    junitxml-path: ./integration-tests/reports/test-report.xml
+      #    coverage-path: ./integration-tests/coverage.txt
 
-      - name: Publish ITest Summary
-        uses: EnricoMi/publish-unit-test-result-action@170bf24d20d201b842d7a52403b73ed297e6645b
-        if: always() && matrix.runner != 'self-hosted'
-        with:
-         check_name: 'Test Results - ${{ matrix.runner }}'
-         files: |
-           **/reports/test-*.xml
+      #- name: Publish ITest Summary
+      #  uses: EnricoMi/publish-unit-test-result-action@170bf24d20d201b842d7a52403b73ed297e6645b
+      #  if: always() && matrix.runner != 'self-hosted'
+      #  with:
+      #   check_name: 'Test Results - ${{ matrix.runner }}'
+      #   files: |
+      #     **/reports/test-*.xml
 
-      - name: Publish ITest Summary
-        uses: EnricoMi/publish-unit-test-result-action/macos@170bf24d20d201b842d7a52403b73ed297e6645b
-        if: always() && matrix.runner == 'self-hosted'
-        with:
-         check_name: 'Test Results - ${{ matrix.runner }}'
-         files: |
-           **/reports/test-*.xml
+      #- name: Publish ITest Summary
+      #  uses: EnricoMi/publish-unit-test-result-action/macos@170bf24d20d201b842d7a52403b73ed297e6645b
+      #  if: always() && matrix.runner == 'self-hosted'
+      #  with:
+      #   check_name: 'Test Results - ${{ matrix.runner }}'
+      #   files: |
+      #     **/reports/test-*.xml
 
-      - name: Publish Test Report CTRF
-        uses: ctrf-io/github-test-reporter@646f98cfc16c6f7a0e1f6100cabe2deb95dd2eef # v1.0.22
-        if: always()
-        with:
-          title: Ledger WASM - Integration test results - ${{ matrix.runner }}
-          report-path: './integration-tests/reports/ctrf-report.json'
-          pull-request-report: true
-          overwrite-comment: true
-          status-check: true
-          comment-tag: '${{ github.workflow }}-${{ github.job }}'
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #- name: Publish Test Report CTRF
+      #  uses: ctrf-io/github-test-reporter@646f98cfc16c6f7a0e1f6100cabe2deb95dd2eef # v1.0.22
+      #  if: always()
+      #  with:
+      #    title: Ledger WASM - Integration test results - ${{ matrix.runner }}
+      #    report-path: './integration-tests/reports/ctrf-report.json'
+      #    pull-request-report: true
+      #    overwrite-comment: true
+      #    status-check: true
+      #    comment-tag: '${{ github.workflow }}-${{ github.job }}'
+      #  env:
+      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Upload Test Results
         uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # ratchet:actions/upload-artifact@v4
@@ -263,7 +262,6 @@ jobs:
       - name: Build and Test (default features)
         run: |
           cargo install cargo2junit
-          nix develop .#ci -c cargo config -Z unstable-options get net.git-fetch-with-cli
           nix develop .#ci -c cargo test --release -- -Z unstable-options --format json --report-time --nocapture --test-threads=1 | tee test-results.json
           cat test-results.json | cargo2junit > ./target/test-results.xml
           cp test-results.json ./target/
